#source 'https://github.com/CocoaPods/Specs.git'
#install! 'cocoapods', :deterministic_uuids => false


platform :ios, '15.0'
inhibit_all_warnings!   #去掉pod里的所有警告
use_frameworks!

target 'Mika' do
  pod 'Alamofire'
  pod 'HandyJSON'
  #pod 'Kingfisher' # 图片加载
  pod 'SnapKit'
  pod 'Reusable'
  pod 'SVProgressHUD'
  #pod 'iCarousel'

  #pod 'YYModel'
  #pod 'MJRefresh'

  #pod 'JXSegmentedView'
  #pod 'JXPagingView/Paging'
  #pod 'IQKeyboardManager'
  
  #pod 'lottie-ios'
  #pod 'KVOController' #安全KVO
  #pod 'CryptoSwift'
  #pod 'YYText'
  #
  
  pod 'ACKit', :path => '/Users/zz/Desktop/workspace/ACKit'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end


end

